stages:
  - stage: 'install'
    jobs:
    - job: install
      steps:
      - script: |
         npm install
         workingDirectory: '$(System.DefaultWorkingDirectory)'
         npm install
  - stage: 'changedir'
    jobs:
    - job: changedir
      steps:
      - script: |
         npm install
         workingDirectory: $(System.DefaultWorkingDirectory)/frontend
         npm install
  - stage: 'BlackDuck_Code_Scan'
    jobs:
    - job: detect
      steps:
      - task: SynopsysDetectTask@9
        inputs:
          BlackDuckService: 'BlackDuck'
          DetectArguments: |
            --detect.project.name=pom_test
            --detect.project.version.name=Ongoing_Build  
            --blackduck.trust.cert=true  
            --detect.detector.search.depth=100  
            --detect.tools=DETECTOR  
            --detect.detector.search.continue=true
          DetectVersion: 'latest'